# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QBP_LzgUyYdz5-jXoxhUdNrmZzitw1Z8
"""

import requests
import pandas as pd
import scipy 
import numpy as nu
import sys

xtrain = pd.read_csv ('linreg_train.csv')
xtest = pd.read_csv ('linreg_test.csv')

x_train = xtrain.iloc[:,1:]
x_test = xtest.iloc[:,1:]
print(x_test)

from sklearn.linear_model import LinearRegression
regresser = LinearRegression()
regresser.fit(x_train,x_test)

